package com.db.macs3.ecomms.spectre.translator;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Splits a NEAR/FOLLOWEDBY tree into independent, gap-less leaf patterns and, in the same
 * pass, renders the same tree as literal-keyword text ({@link Result#resolvedText()}).
 *
 * <p><b>Role in the pipeline.</b> {@link #decompose} runs for every side of every term.
 * {@code TermSyntaxTranslator#resolveSide} then decides whether {@code regexPattern} uses
 * these leaves (the FALLBACK, for a side too large to compile as one pattern) or one
 * self-contained gap-embedded pattern (preferred whenever Hyperscan accepts it).
 * {@link Result#resolvedText()} is what {@code resolvedPatterns} reports either way.
 *
 * <p><b>Leaves carry no gap.</b> The NEAR/FOLLOWEDBY distance and order are never compiled
 * into a leaf. They exist only in {@code resolvedText}, rendered as literal
 * {@code " NEAR{n} "} / {@code " FOLLOWEDBY{n} "} using the author's raw distance.
 * Leaves are combined with boolean AND, so a consumer of a decomposed term must read
 * {@code resolvedPatterns} to enforce the proximity between leaves (see
 * {@link com.db.macs3.ecomms.spectre.model.TermCompilationResult#resolvedPatterns()}; the test tree's {@code ResolvedPatternMatcher}
 * is a reference implementation of that consumer logic).
 *
 * <p><b>Right-side nesting keeps its grouping.</b> When the RIGHT operand of a proximity
 * node is itself a proximity node, its rendering is wrapped in one extra pair of
 * parentheses: {@code "(manipulate OR front run) NEAR{5} ((price OR spread) NEAR{5} stock)"}
 * renders as {@code "(?:manipulate|front run) NEAR{5} ((?:price|spread) NEAR{5} stock)"}
 * with {@code formulaTemplate} {@code "{0}&({1}&{2})"}. The LEFT side is never wrapped: a flat
 * left-to-right rendering already means left-associative nesting, which is also what an
 * unparenthesised chain parses to. See {@link #decomposeProximity}.
 *
 * <p><b>NEAR/FOLLOWEDBY inside {@code OR} is not decomposed.</b> A multi-operand
 * {@code Ast.Or} is one opaque leaf generated by {@link PatternCodeGenerator#generate},
 * because flattening an OR alternative into AND'd leaves would change what the OR means
 * (it would need {@code regexPattern} to be a nested structure, not a flat list). Such a
 * term, e.g. {@code "(plain phrase) OR ((EURIBOR FIXING) NEAR{2} TENOR)"}, therefore always
 * compiles as one gap-embedded pattern through {@code generateNear}/{@code generateFollowedBy}
 * and {@link MultiLanguagePatternBuilder}, and has no fallback.
 *
 * <p><b>{@code AND} with nested proximity is flattened, losslessly.</b> AND already means
 * "every operand present somewhere, any order, any distance" — exactly "all these leaves are
 * present". When an {@code And} contains NEAR/FOLLOWEDBY ({@link #containsProximity}) its
 * operands are decomposed individually; an {@code And} with no nested proximity stays one
 * opaque permutation pattern.
 */
final class PatternDecomposer {

    private PatternDecomposer() {
    }

    /**
     * One decomposed subtree.
     *
     * @param leaves          independent PCRE fragments, each individually Hyperscan-compilable,
     *                        in left-to-right term order, containing no gap fragment
     * @param resolvedText    the subtree rendered with literal {@code NEAR{n}} /
     *                        {@code FOLLOWEDBY{n}} / {@code AND} keyword text (see the class
     *                        Javadoc for when extra grouping parentheses appear). Every leaf
     *                        appears in it byte-for-byte, in the same order as in {@code leaves}
     * @param formulaTemplate the same subtree's boolean-AND structure with {@code {i}}
     *                        placeholders (0-based indexes into THIS result's {@code leaves})
     *                        and {@code &} in place of each keyword, e.g. {@code "{0}&({1}&{2})"}.
     *                        It mirrors {@code resolvedText}'s grouping, so
     *                        {@code HyperscanCombinationHandler} can substitute each placeholder
     *                        with the leaf's Hyperscan expression id to build
     *                        {@code patternMapping} and the native COMBINATION formula
     */
    record Result(List<String> leaves, String resolvedText, String formulaTemplate) {
    }

    /**
     * Matches one {@code {i}} leaf-index placeholder in a {@link Result#formulaTemplate()}.
     */
    private static final Pattern FORMULA_PLACEHOLDER = Pattern.compile("\\{(\\d+)}");

    /**
     * Re-indexes every {@code {i}} placeholder in {@code template} by adding
     * {@code offset} — used when splicing a sub-Result's own (locally
     * 0-based) formula template into a larger combined leaf list, exactly the
     * way {@code leaves} lists are concatenated.
     */
    private static String shiftFormulaPlaceholders(String template, int offset) {
        if (offset == 0) {
            return template;
        }
        Matcher matcher = FORMULA_PLACEHOLDER.matcher(template);
        StringBuilder shifted = new StringBuilder();
        while (matcher.find()) {
            matcher.appendReplacement(shifted, "{" + (Integer.parseInt(matcher.group(1)) + offset) + "}");
        }
        matcher.appendTail(shifted);
        return shifted.toString();
    }

    /**
     * Decomposes {@code ast}. A leaf root simply yields one leaf whose {@code resolvedText}
     * is that leaf's own pattern.
     *
     * @param ctx shared parse context, mutated with UTF8/UCP needs and warnings exactly as
     *            {@link PatternCodeGenerator#generate} would. Each node is visited once, by
     *            this single pass, so {@code leaves} and {@code resolvedText} can never disagree
     */
    static Result decompose(Ast ast, ParseContext ctx) {
        return switch (ast) {
            case Ast.Near near -> decomposeProximity(near.left(), near.right(), near.distance(), "NEAR", ctx);
            case Ast.FollowedBy fb -> decomposeProximity(fb.left(), fb.right(), fb.distance(), "FOLLOWEDBY", ctx);

            // A single-operand Or is not something the parser itself ever produces
            // (ExpressionParser.parseOr unwraps a lone alternative directly) — it only
            // arises from TermSyntaxTranslator wrapping an AND NOT term's excluded
            // operand list in an Or even when there is exactly one operand, specifically
            // to keep the generated exclusionRegex string's "(?:...)" wrapping identical
            // to before decomposition existed. Seeing through it here means that single
            // excluded operand's OWN proximity structure (if any) is still visible to
            // decomposition, rather than the Or wrapper being treated as one opaque leaf.
            case Ast.Or or when or.operands().size() == 1 -> decompose(or.operands().getFirst(), ctx);

            // AND is flattened only when it actually contains nested proximity — see
            // class Javadoc. A plain AND (no nested NEAR/FOLLOWEDBY anywhere) falls
            // through to the default arm below, unaffected.
            case Ast.And and when containsProximity(and) -> decomposeAnd(and, ctx);

            case Ast.Not ignored -> throw new IllegalStateException(
                    "unreachable — every Ast.Not is folded into Ast.AndNot (or rejected) by "
                    + "ExpressionParser.parseAnd() before an Ast is ever returned; see Ast.Not Javadoc");

            // Every other case — a multi-operand Or (including one that itself contains
            // nested proximity — see class Javadoc "the one exception"), a plain And with
            // no nested proximity, Word, Phrase, QuotedPhrase — is one opaque leaf,
            // generated exactly as PatternCodeGenerator already would for a non-decomposed
            // term. resolvedText is deliberately the SAME string, not a re-derivation, so
            // it can never drift from what regexPattern/exclusionRegex actually contain.
            default -> {
                String pattern = PatternCodeGenerator.generate(ast, ctx);
                yield new Result(List.of(pattern), pattern, "{0}");
            }
        };
    }

    /**
     * Decomposes both operands of one NEAR/FOLLOWEDBY node and joins them: {@code left}'s
     * leaves followed by {@code right}'s (no gap fragment added), with
     * {@code resolvedText} joining the two renderings by {@code " KEYWORD{distance} "}.
     * A right operand that is itself proximity is wrapped in parentheses in both
     * {@code resolvedText} and {@code formulaTemplate}; a left operand never is (see the class
     * Javadoc for why).
     */
    private static Result decomposeProximity(Ast left, Ast right, int distance, String keyword, ParseContext ctx) {
        Result leftResult = decompose(left, ctx);
        Result rightResult = decompose(right, ctx);

        List<String> combined = new ArrayList<>(leftResult.leaves().size() + rightResult.leaves().size());
        combined.addAll(leftResult.leaves());
        combined.addAll(rightResult.leaves());

        boolean rightIsNestedProximity = right instanceof Ast.Near || right instanceof Ast.FollowedBy;

        String rightResolvedText = rightIsNestedProximity
                ? "(" + rightResult.resolvedText() + ")" : rightResult.resolvedText();
        String resolvedText = leftResult.resolvedText() + " " + keyword + "{" + distance + "} " + rightResolvedText;

        String shiftedRightFormula = shiftFormulaPlaceholders(rightResult.formulaTemplate(), leftResult.leaves().size());
        String rightFormula = rightIsNestedProximity ? "(" + shiftedRightFormula + ")" : shiftedRightFormula;
        String formulaTemplate = leftResult.formulaTemplate() + "&" + rightFormula;

        return new Result(combined, resolvedText, formulaTemplate);
    }

    /**
     * Flattens an {@code And} known (via {@link #containsProximity}) to contain proximity:
     * every operand is decomposed and the leaves concatenated. {@code resolvedText} and
     * {@code formulaTemplate} join operands with {@code " AND "} / {@code "&"}, never
     * parenthesised, since AND is commutative and associative.
     */
    private static Result decomposeAnd(Ast.And and, ParseContext ctx) {
        List<String> combined = new ArrayList<>();
        StringBuilder resolvedText = new StringBuilder();
        StringBuilder formulaTemplate = new StringBuilder();
        boolean first = true;
        for (Ast operand : and.operands()) {
            Result operandResult = decompose(operand, ctx);
            formulaTemplate.append(first ? "" : "&")
                    .append(shiftFormulaPlaceholders(operandResult.formulaTemplate(), combined.size()));
            combined.addAll(operandResult.leaves());
            if (!first) {
                resolvedText.append(" AND ");
            }
            resolvedText.append(operandResult.resolvedText());
            first = false;
        }
        return new Result(combined, resolvedText.toString(), formulaTemplate.toString());
    }

    /**
     * True when {@code ast} contains a NEAR/FOLLOWEDBY reachable by recursing only through
     * {@link Ast.And}. {@link Ast.Or} is deliberately not recursed into — it is always one
     * opaque leaf (see the class Javadoc).
     */
    private static boolean containsProximity(Ast ast) {
        return switch (ast) {
            case Ast.Near ignored -> true;
            case Ast.FollowedBy ignored -> true;
            case Ast.And and -> and.operands().stream().anyMatch(PatternDecomposer::containsProximity);
            default -> false;
        };
    }
}
